Sample profiling
Clinical-Genomics/loqusdb pull request #61
Opened 2019-03-21 14:33 UTC by adrosenbaum

Implementation of sample profiling.

User must first load 'profile variants' to the profile_variant collection
    loqusdb profile <vcf_file>

To activate the profiling function when using the load subcommand give the --check-profiles flag and --profile-threshold option
    loqusdb load ... --check-profiles --profile-theshold <float 0-1>

This will check the genotype of all samples in a vcf-file (not sv), at the positions of the profile_variants in the 'profile_variant' collection. The profile is assembled as a string for each sample. The profiles are checked against all profiles of previous samples in the database. If the check passes, the case and its variants are loaded. The profile string is found in the 'case' collection for each individual.

todo in this PR:
    tests

2019-03-22 08:10 UTC, moonso commented
Hi @adrosenbaum , nice work! I'll wait for the tests and start with the review then. It makes it easier to see what is going on.

2019-03-25 12:13 UTC, moonso requested changes
Nice work @adrosenbaum !! I like the testing as well.
There where some comments, minor stuff. Could you add some stuff to the documentation? It needs to be explained somewhere why this is here and how it works

2019-03-25 12:13 UTC, moonso commented on loqusdb/build_models/profile_variant.py
> +        the alt allele
Could you follow the `Args: Returns:` syntax? Also can you elaborate a little bit more. What type is returned?

2019-03-25 12:13 UTC, moonso commented on loqusdb/build_models/profile_variant.py
> +
To make it more flat:
```python
if not variant.INFO.get('CAF'):
    return None
maf_list = json.loads(variant.INFO.get('CAF'))
return maf_list[1]
```

2019-03-25 12:13 UTC, moonso commented on loqusdb/commands/load.py
> +    else:
```suggestion

```

2019-03-25 12:13 UTC, moonso commented on loqusdb/commands/load.py
> +        return value
```suggestion
    return value
```

2019-03-25 12:13 UTC, moonso commented on loqusdb/commands/load_profile.py
> +
Please add a doctring with some more information like:
```python
"""
Takes a vcf with variants choosen for profile

Profiling is used when...
....
...
"""
```

2019-03-25 12:13 UTC, moonso commented on loqusdb/plugins/mongo/adapter.py
> +from . import VariantMixin, CaseMixin, ProfileVariantMixin
```suggestion
from . import (VariantMixin, CaseMixin, ProfileVariantMixin)
```

2019-03-25 12:13 UTC, moonso commented on loqusdb/plugins/mongo/profile_variant.py
> +        """Add several variants to database
```suggestion
        """Add several variants to the profile collection in the database
```

2019-03-25 12:13 UTC, moonso commented on loqusdb/utils/profiling.py
> +
Could you write some more about what is happening when a match is found?

2019-03-26 08:40 UTC, adrosenbaum commented
Fixed what you commented on @moonso. 

I've also added a functionality that will update the profiles of existing samples in the database, if a path to a snv VCF file is given for the case. (loqusdb profile --update).

There is also a feature 'loqusdb profile --stats' that I thought should print some statistics based on the profiles. I am however unsure of what statistics might be useful to look at (or if this feature is necessary at all). Now it calculates the pair wise hamming distance between all sample profiles in the DB, and calculates the mean, and std, to get an idea of how well the samples can be distinguished from each other using this method.

2019-03-27 13:43 UTC, adrosenbaum commented
Pushed some new commits.

Do you have the possibility to review this soon @moonso? It would be nice to test this branch tomorrow on stage.

2019-03-28 09:24 UTC, moonso approved these changes

2019-04-04 07:58 UTC, adrosenbaum commented
Hopefully final change.

When loading a case, the vcf that the profiling is made on is entered separate from the variants that is to be loaded into the db. The 'profile' vcf is given with the --check-profile option. Any thoughts @moonso and @henrikstranneheim?

2019-04-05 06:48 UTC, henrikstranneheim commented
@moonso Do you have time to look at this PR today?

2019-04-05 07:01 UTC, moonso commented
Ok I'll have a look sometime today!

2019-04-05 07:04 UTC, henrikstranneheim commented
👍

2019-04-05 08:04 UTC, moonso approved these changes
Looks great @adrosenbaum ! All I would like now are a couple of lines in the documentation about the idea of the profiling feature. Why it is there and why one needs to point to another VCF than the load vcf. This might be clear to us but if another user is uploading it would be nice to have it in the docs. 👍

2019-04-05 08:05 UTC, moonso commented
Oh and can you update the CHANGELOG.md?

2019-04-05 08:56 UTC, adrosenbaum commented
Added to documentation and CHANGELOG.md. Does this sufficiently describe the new profiling feature @moonso? If so I'll merge with master.

2019-04-05 11:33 UTC, moonso commented
Great! Go ahead

2019-04-05 11:34 UTC, merged